window.SLOT_VALLEY_GAMES = [
  {
    name: "Juwa",
    image: "assets/games/juwa.webp",
    player: "https://dl.juwa777.com/",
    agent: "http://ht.juwa777.com/",
  },
  {
    name: "Juwa2",
    image: "assets/games/juwa2.webp",
    player: "https://dl.juwa2.com/",
    agent: "http://ht.juwa2.com/",
  },
  {
    name: "GameVault",
    image: "assets/games/gamevault.webp",
    player: "https://download.gamevault999.com/",
    agent: "http://agent.gamevault999.com/",
  },
  {
    name: "Firekirin",
    image: "assets/games/firekirin.webp",
    player: "https://firekirin.com/",
    agent: "https://firekirin.xyz:8888/Store.aspx",
  },
  {
    name: "Orionstar",
    image: "assets/games/orionstar.webp",
    player: "http://start.orionstars.vip:8580/index.html",
    agent: "https://orionstars.vip:8781/Store.aspx",
  },
  {
    name: "CasinoRoyale",
    image: "assets/games/casinoroyale.webp",
    player: "http://m.casinoroyale07.com/",
    agent: "http://agent.casinoroyale07.com/adminList",
  },
  {
    name: "VegasSweep",
    image: "assets/games/vegassweep.webp",
    player: "http://m.lasvegassweeps.com/",
    agent: "http://agent.lasvegassweeps.com/adminList",
  },
  {
    name: "MilkyWay",
    image: "assets/games/milkyway.webp",
    player: "https://milkywayapp.xyz/",
    agent: "https://milkywayapp.xyz:8781/Store.aspx",
  },
  {
    name: "Ultra Panda",
    image: "assets/games/ultra-panda.webp",
    player: "https://www.ultrapanda.mobi/",
    agent: "https://ht.ultrapanda.mobi/#/manage-user/account",
  },
  {
    name: "Cash Frenzy",
    image: "assets/games/cash-frenzy.webp",
    player: "https://www.cashfrenzy777.com/",
    agent: "https://agentserver.cashfrenzy777.com/admin/login",
  },
  {
    name: "Pandamaster",
    image: "assets/games/pandamaster.webp",
    player: "https://pandamaster.vip:8888/index.html",
    agent: "https://pandamaster.vip/default.aspx",
  },
  {
    name: "Vblink",
    image: "assets/games/vblink.webp",
    player: "http://www.vblink777.club/",
    agent: "http://gm.vblink777.club/",
  },
  {
    name: "River Sweeps",
    image: "assets/games/river-sweeps.webp",
    player: "https://bet777.eu/",
    agent: "http://river-pay.com/office/login",
  },
  {
    name: "HighStake",
    image: "assets/games/highstake.webp",
    player: "http://dl.highstakesweeps.com/",
    agent: "https://ht.highstakesweeps.com/userManagement",
  },
  {
    name: "VegasX",
    image: "assets/games/vegasx.webp",
    player: "https://www.vegas-x.org/",
    agent: "https://cashier.vegas-x.org/login",
  },
  {
    name: "Game Room",
    image: "assets/games/game-room.webp",
    player: "https://www.gameroom777.com/",
    agent: "https://agentserver1.gameroom777.com/admin/login",
  },
  {
    name: "Blue Dragon",
    image: "assets/games/blue-dragon.webp",
    player: "http://app.bluedragon777.com/",
    agent: "http://agent.bluedragon777.com/Login.aspx",
  },
  {
    name: "Para",
    image: "assets/games/para.webp",
    player: "http://download.paracasino.net/",
    agent: "http://agent.paracasino.net/",
  },
  {
    name: "River Monster",
    image: "assets/games/river-monster.webp",
    player: "https://rm777.net/",
    agent: "https://rm777.net/",
  },
  {
    name: "Moolah",
    image: "assets/games/moolah.webp",
    player: "https://moolah.vip:8888/",
    agent: "https://moolah.vip:8781/default.aspx",
  },
  {
    name: "Sirius",
    image: "assets/games/sirius.webp",
    player: "https://m.gamesirius999.com/",
    agent: "https://agent.gamesirius999.com/login",
  },
  {
    name: "Mega Spin",
    image: "assets/games/mega-spin.webp",
    player: "https://www.megaspinsweeps.com/",
    agent: "https://megaspinpay.com/default.aspx",
  },
  {
    name: "Egames",
    image: "assets/games/egames.webp",
    player: "https://www.egame99.club/",
    agent: "https://pko.egame99.club/#/login",
  },
  {
    name: "Loot",
    image: "assets/games/loot.webp",
    player: "http://m.lootgame777.com/",
    agent: "http://client.lootgame777.com/login",
  },
  {
    name: "Casino Ignite",
    image: "assets/games/casino-ignite.webp",
    player: "https://download.casinoignitee.vip/",
    agent: "https://agent.casinoignitee.vip/auth/login",
  },
  {
    name: "Cash Machine",
    image: "assets/games/cash-machine.webp",
    player: "https://www.cashmachine777.com/",
    agent: "https://agentserver.cashmachine777.com/admin/login",
  },
  {
    name: "Vegas Roll",
    image: "assets/games/vegas-roll.webp",
    player: "https://www.vegas-roll.com/",
    agent: "https://backend.vegas-roll.com/admin/login",
  },
  {
    name: "Win Star",
    image: "assets/games/win-star.webp",
    player: "http://server.winstar99999.com:8009/",
    agent: "https://agent.winstar99999.com/admin/login",
  },
  {
    name: "Yolo",
    image: "assets/games/yolo.webp",
    player: "https://yolo777.game/",
    agent: "https://agent.yolo777.game/admin/auth/login",
  },
  {
    name: "Joker",
    image: "assets/games/joker.webp",
    player: "https://joker777.win/",
    agent: "https://agent.joker777.win/admin/login",
  }
];
